// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SisConf.Infrastructure.Persistencia;

#nullable disable

namespace SisConf.Infrastructure.Persistencia.Migrations
{
    [DbContext(typeof(SisConfDbContext))]
    [Migration("20260519061732_Relatorios")]
    partial class Relatorios
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SisConf.Domain.Cadastros.Box", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TtsTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tts_texto");

                    b.HasKey("Id")
                        .HasName("pk_box");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_box_tenant_id_codigo");

                    b.ToTable("box", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.Grupo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("CriadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("criado_por_usuario_id");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nome");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_grupo");

                    b.HasIndex("CriadoPorUsuarioId")
                        .HasDatabaseName("ix_grupo_criado_por_usuario_id");

                    b.HasIndex("TenantId", "Nome")
                        .HasDatabaseName("ix_grupo_tenant_id_nome");

                    b.ToTable("grupo", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.Layout", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("ExemploArquivoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exemplo_arquivo_url");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<string>("ParserKey")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("parser_key");

                    b.HasKey("Id")
                        .HasName("pk_layout");

                    b.HasIndex("ParserKey")
                        .IsUnique()
                        .HasDatabaseName("ix_layout_parser_key");

                    b.ToTable("layout", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.Status", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<string>("CorHex")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("character varying(9)")
                        .HasColumnName("cor_hex");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EhBloqueio")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_bloqueio");

                    b.Property<bool>("EhInicial")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_inicial");

                    b.Property<bool>("EhTerminal")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_terminal");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TtsTexto")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tts_texto");

                    b.HasKey("Id")
                        .HasName("pk_status");

                    b.HasIndex("TenantId", "Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_status_tenant_id_codigo");

                    b.HasIndex("TenantId", "Ordem")
                        .HasDatabaseName("ix_status_tenant_id_ordem");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.TenantLayoutAtivo", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<DateTime>("AtivadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ativado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("AtivadoPorUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ativado_por_usuario_id");

                    b.HasKey("TenantId", "LayoutId")
                        .HasName("pk_tenant_layout_ativo");

                    b.HasIndex("AtivadoPorUsuarioId")
                        .HasDatabaseName("ix_tenant_layout_ativo_ativado_por_usuario_id");

                    b.HasIndex("LayoutId")
                        .HasDatabaseName("ix_tenant_layout_ativo_layout_id");

                    b.ToTable("tenant_layout_ativo", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Conferencia.Pedido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ArquivoImportacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquivo_importacao_id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("BoxId")
                        .HasColumnType("uuid")
                        .HasColumnName("box_id");

                    b.Property<string>("Cliente")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("cliente");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("descricao");

                    b.Property<string>("Etiqueta")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("etiqueta");

                    b.Property<Guid?>("GrupoId")
                        .HasColumnType("uuid")
                        .HasColumnName("grupo_id");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<DateTime?>("LockExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lock_expires_at");

                    b.Property<string>("LockSessionId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("lock_session_id");

                    b.Property<Guid?>("LockUsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("lock_usuario_id");

                    b.Property<string>("OrdemCompra")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ordem_compra");

                    b.Property<string>("PeCliente")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("pe_cliente");

                    b.Property<string>("Produto")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("produto");

                    b.Property<int?>("Qtde")
                        .HasColumnType("integer")
                        .HasColumnName("qtde");

                    b.Property<long?>("Sequencia")
                        .HasColumnType("bigint")
                        .HasColumnName("sequencia");

                    b.Property<Guid>("StatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Volume")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("volume");

                    b.HasKey("Id")
                        .HasName("pk_pedido");

                    b.HasIndex("BoxId")
                        .HasDatabaseName("ix_pedido_box_id");

                    b.HasIndex("GrupoId")
                        .HasDatabaseName("ix_pedido_grupo_id");

                    b.HasIndex("LayoutId")
                        .HasDatabaseName("ix_pedido_layout_id");

                    b.HasIndex("LockUsuarioId")
                        .HasDatabaseName("ix_pedido_lock_usuario_id");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_pedido_status_id");

                    b.HasIndex("TenantId", "ArquivoImportacaoId")
                        .HasDatabaseName("ix_pedido_tenant_id_arquivo_importacao_id");

                    b.HasIndex("TenantId", "Etiqueta")
                        .HasDatabaseName("ix_pedido_tenant_id_etiqueta");

                    b.HasIndex("TenantId", "GrupoId")
                        .HasDatabaseName("ix_pedido_tenant_id_grupo_id");

                    b.HasIndex("TenantId", "StatusId", "BoxId")
                        .HasDatabaseName("ix_pedido_tenant_id_status_id_box_id");

                    b.ToTable("pedido", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Conferencia.PedidoEvento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid>("ClientEventId")
                        .HasColumnType("uuid")
                        .HasColumnName("client_event_id");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata_json");

                    b.Property<DateTime>("OcorreuEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorreu_em");

                    b.Property<string>("Origem")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origem");

                    b.Property<Guid>("PedidoId")
                        .HasColumnType("uuid")
                        .HasColumnName("pedido_id");

                    b.Property<Guid?>("StatusAnteriorId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_anterior_id");

                    b.Property<Guid>("StatusNovoId")
                        .HasColumnType("uuid")
                        .HasColumnName("status_novo_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_pedido_evento");

                    b.HasIndex("ClientEventId")
                        .IsUnique()
                        .HasDatabaseName("ix_pedido_evento_client_event_id");

                    b.HasIndex("PedidoId")
                        .HasDatabaseName("ix_pedido_evento_pedido_id");

                    b.HasIndex("StatusNovoId")
                        .HasDatabaseName("ix_pedido_evento_status_novo_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_pedido_evento_usuario_id");

                    b.HasIndex("TenantId", "OcorreuEm")
                        .HasDatabaseName("ix_pedido_evento_tenant_id_ocorreu_em");

                    b.HasIndex("TenantId", "PedidoId", "OcorreuEm")
                        .HasDatabaseName("ix_pedido_evento_tenant_id_pedido_id_ocorreu_em");

                    b.HasIndex("TenantId", "UsuarioId", "OcorreuEm")
                        .HasDatabaseName("ix_pedido_evento_tenant_id_usuario_id_ocorreu_em");

                    b.ToTable("pedido_evento", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Faturamento.Plano", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("codigo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("LimiteImportacoesMes")
                        .HasColumnType("integer")
                        .HasColumnName("limite_importacoes_mes");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer")
                        .HasColumnName("ordem");

                    b.Property<int>("PrecoMensalCentavos")
                        .HasColumnType("integer")
                        .HasColumnName("preco_mensal_centavos");

                    b.Property<string>("RecursosJson")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasDefaultValue("{}")
                        .HasColumnName("recursos_json");

                    b.Property<string>("StripePriceId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stripe_price_id");

                    b.HasKey("Id")
                        .HasName("pk_plano");

                    b.HasIndex("Codigo")
                        .IsUnique()
                        .HasDatabaseName("ix_plano_codigo");

                    b.ToTable("plano", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Faturamento.UsoMensal", b =>
                {
                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int>("AnoMes")
                        .HasColumnType("integer")
                        .HasColumnName("ano_mes");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("ImportacoesCount")
                        .HasColumnType("integer")
                        .HasColumnName("importacoes_count");

                    b.Property<int>("PedidosProcessadosCount")
                        .HasColumnType("integer")
                        .HasColumnName("pedidos_processados_count");

                    b.HasKey("TenantId", "AnoMes")
                        .HasName("pk_uso_mensal");

                    b.ToTable("uso_mensal", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.Permissao", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("codigo");

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("acao");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<string>("Modulo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("modulo");

                    b.HasKey("Codigo")
                        .HasName("pk_permissao");

                    b.ToTable("permissao", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.RefreshToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("ExpiraEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expira_em");

                    b.Property<string>("IpOrigem")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("ip_origem");

                    b.Property<DateTime?>("RevogadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revogado_em");

                    b.Property<Guid?>("SubstituidoPorId")
                        .HasColumnType("uuid")
                        .HasColumnName("substituido_por_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("token_hash");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("user_agent");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_refresh_token");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_refresh_token_tenant_id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_refresh_token_token_hash");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_refresh_token_usuario_id");

                    b.ToTable("refresh_token", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Descricao")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descricao");

                    b.Property<bool>("EhSistema")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_sistema");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("nome");

                    b.Property<Guid?>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_role");

                    b.HasIndex("TenantId", "Nome")
                        .IsUnique()
                        .HasDatabaseName("ix_role_tenant_id_nome");

                    b.ToTable("role", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.RolePermissao", b =>
                {
                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.Property<string>("PermissaoCodigo")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("permissao_codigo");

                    b.HasKey("RoleId", "PermissaoCodigo")
                        .HasName("pk_role_permissao");

                    b.HasIndex("PermissaoCodigo")
                        .HasDatabaseName("ix_role_permissao_permissao_codigo");

                    b.ToTable("role_permissao", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean")
                        .HasColumnName("ativo");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<bool>("EhOwner")
                        .HasColumnType("boolean")
                        .HasColumnName("eh_owner");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("senha_hash");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UltimoLoginEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ultimo_login_em");

                    b.HasKey("Id")
                        .HasName("pk_usuario");

                    b.HasIndex("TenantId", "Email")
                        .IsUnique()
                        .HasDatabaseName("ix_usuario_tenant_id_email");

                    b.ToTable("usuario", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.UsuarioRole", b =>
                {
                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UsuarioId", "RoleId")
                        .HasName("pk_usuario_role");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_usuario_role_role_id");

                    b.ToTable("usuario_role", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Importacao.ArquivoImportacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<Guid>("LayoutId")
                        .HasColumnType("uuid")
                        .HasColumnName("layout_id");

                    b.Property<int>("LinhasErro")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_erro");

                    b.Property<int>("LinhasOk")
                        .HasColumnType("integer")
                        .HasColumnName("linhas_ok");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensagem_erro");

                    b.Property<string>("NomeArquivo")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("nome_arquivo");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<long>("StorageTamanhoBytes")
                        .HasColumnType("bigint")
                        .HasColumnName("storage_tamanho_bytes");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("TotalLinhas")
                        .HasColumnType("integer")
                        .HasColumnName("total_linhas");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_arquivo_importacao");

                    b.HasIndex("LayoutId")
                        .HasDatabaseName("ix_arquivo_importacao_layout_id");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_arquivo_importacao_usuario_id");

                    b.HasIndex("TenantId", "CriadoEm")
                        .HasDatabaseName("ix_arquivo_importacao_tenant_id_criado_em");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_arquivo_importacao_tenant_id_status");

                    b.ToTable("arquivo_importacao", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Importacao.ArquivoImportacaoErro", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArquivoImportacaoId")
                        .HasColumnType("uuid")
                        .HasColumnName("arquivo_importacao_id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Conteudo")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("conteudo");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("mensagem");

                    b.Property<int>("NumeroLinha")
                        .HasColumnType("integer")
                        .HasColumnName("numero_linha");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_arquivo_importacao_erro");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_arquivo_importacao_erro_tenant_id");

                    b.HasIndex("ArquivoImportacaoId", "NumeroLinha")
                        .HasDatabaseName("ix_arquivo_importacao_erro_arquivo_importacao_id_numero_linha");

                    b.ToTable("arquivo_importacao_erro", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Relatorios.RelatorioJob", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime?>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finalizado_em");

                    b.Property<DateTime?>("IniciadoEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("iniciado_em");

                    b.Property<string>("MensagemErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("mensagem_erro");

                    b.Property<string>("ParametrosJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parametros_json");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StorageKey")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("storage_key");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("tipo");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid")
                        .HasColumnName("usuario_id");

                    b.HasKey("Id")
                        .HasName("pk_relatorio_job");

                    b.HasIndex("UsuarioId")
                        .HasDatabaseName("ix_relatorio_job_usuario_id");

                    b.HasIndex("TenantId", "CriadoEm")
                        .HasDatabaseName("ix_relatorio_job_tenant_id_criado_em");

                    b.ToTable("relatorio_job", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Tenants.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("AtualizadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTime>("CriadoEm")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("criado_em")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Documento")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("documento");

                    b.Property<string>("EmailAdmin")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("email_admin");

                    b.Property<Guid?>("PlanoId")
                        .HasColumnType("uuid")
                        .HasColumnName("plano_id");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("razao_social");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("StripeCustomerId")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("stripe_customer_id");

                    b.Property<string>("Telefone")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("telefone");

                    b.Property<DateTime?>("TrialTerminaEm")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trial_termina_em");

                    b.HasKey("Id")
                        .HasName("pk_tenant");

                    b.HasIndex("PlanoId")
                        .HasDatabaseName("ix_tenant_plano_id");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_slug");

                    b.HasIndex("StripeCustomerId")
                        .IsUnique()
                        .HasDatabaseName("ix_tenant_stripe_customer_id")
                        .HasFilter("stripe_customer_id IS NOT NULL");

                    b.ToTable("tenant", (string)null);
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.Box", b =>
                {
                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_box_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.Grupo", b =>
                {
                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("CriadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_grupo_usuario_criado_por_usuario_id");

                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_grupo_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.Status", b =>
                {
                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_status_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Cadastros.TenantLayoutAtivo", b =>
                {
                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("AtivadoPorUsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_layout_ativo_usuario_ativado_por_usuario_id");

                    b.HasOne("SisConf.Domain.Cadastros.Layout", null)
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_layout_ativo_layout_layout_id");

                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_tenant_layout_ativo_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Conferencia.Pedido", b =>
                {
                    b.HasOne("SisConf.Domain.Cadastros.Box", null)
                        .WithMany()
                        .HasForeignKey("BoxId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedido_box_box_id");

                    b.HasOne("SisConf.Domain.Cadastros.Grupo", null)
                        .WithMany()
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedido_grupo_grupo_id");

                    b.HasOne("SisConf.Domain.Cadastros.Layout", null)
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_layout_layout_id");

                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("LockUsuarioId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_pedido_usuario_lock_usuario_id");

                    b.HasOne("SisConf.Domain.Cadastros.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_status_status_id");

                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Conferencia.PedidoEvento", b =>
                {
                    b.HasOne("SisConf.Domain.Conferencia.Pedido", null)
                        .WithMany()
                        .HasForeignKey("PedidoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_evento_pedido_pedido_id");

                    b.HasOne("SisConf.Domain.Cadastros.Status", null)
                        .WithMany()
                        .HasForeignKey("StatusNovoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_evento_status_status_novo_id");

                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_evento_tenant_tenant_id");

                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pedido_evento_usuario_usuario_id");
                });

            modelBuilder.Entity("SisConf.Domain.Faturamento.UsoMensal", b =>
                {
                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_uso_mensal_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.RefreshToken", b =>
                {
                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_tenant_tenant_id");

                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_refresh_token_usuario_usuario_id");
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.RolePermissao", b =>
                {
                    b.HasOne("SisConf.Domain.Identidade.Permissao", null)
                        .WithMany()
                        .HasForeignKey("PermissaoCodigo")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissao_permissao_permissao_codigo");

                    b.HasOne("SisConf.Domain.Identidade.Role", null)
                        .WithMany("Permissoes")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissao_role_role_id");
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.Usuario", b =>
                {
                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.UsuarioRole", b =>
                {
                    b.HasOne("SisConf.Domain.Identidade.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_role_role_role_id");

                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany("Roles")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_usuario_role_usuario_usuario_id");
                });

            modelBuilder.Entity("SisConf.Domain.Importacao.ArquivoImportacao", b =>
                {
                    b.HasOne("SisConf.Domain.Cadastros.Layout", null)
                        .WithMany()
                        .HasForeignKey("LayoutId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_arquivo_importacao_layout_layout_id");

                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arquivo_importacao_tenant_tenant_id");

                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_arquivo_importacao_usuario_usuario_id");
                });

            modelBuilder.Entity("SisConf.Domain.Importacao.ArquivoImportacaoErro", b =>
                {
                    b.HasOne("SisConf.Domain.Importacao.ArquivoImportacao", null)
                        .WithMany()
                        .HasForeignKey("ArquivoImportacaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arquivo_importacao_erro_arquivo_importacao_arquivo_importac~");

                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_arquivo_importacao_erro_tenant_tenant_id");
                });

            modelBuilder.Entity("SisConf.Domain.Relatorios.RelatorioJob", b =>
                {
                    b.HasOne("SisConf.Domain.Tenants.Tenant", null)
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_relatorio_job_tenant_tenant_id");

                    b.HasOne("SisConf.Domain.Identidade.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_relatorio_job_usuario_usuario_id");
                });

            modelBuilder.Entity("SisConf.Domain.Tenants.Tenant", b =>
                {
                    b.HasOne("SisConf.Domain.Faturamento.Plano", null)
                        .WithMany()
                        .HasForeignKey("PlanoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tenant_plano_plano_id");
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.Role", b =>
                {
                    b.Navigation("Permissoes");
                });

            modelBuilder.Entity("SisConf.Domain.Identidade.Usuario", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
