-- =============================================================================
-- SysConf - Log de conferencia (auditoria da bipagem)
-- Arquivo : supabase/migrations/20260919000109_log_conferencia.sql
--
-- OBJETIVO (pedido do cliente): registrar CADA leitura que o operador faz na
-- conferencia -- em qualquer estagio (1=CONFERENCIA, 2=SAIDA, 3=ENTREGA) --
-- inclusive as bipagens erradas ("Etiqueta nao encontrada !"), as repetidas
-- ("Etiqueta ja lida !"), as fora de ordem ("Esta etiqueta esta para SAIDA") e
-- tambem as alteracoes em massa feitas pelo menu de contexto. O ADMINISTRADOR
-- ve tudo em uma tela, com filtros e exportacao CSV.
--
-- DESENHO:
--   1. `log_conferencia` = uma linha por leitura/alteracao, com os dados
--      DENORMALIZADOS (fabrica, etiqueta, produto, box, status antes/depois).
--      Denormalizado de proposito: o log e auditoria e precisa continuar
--      legivel DEPOIS de o pedido ser apagado (excluir uma importacao apaga os
--      pedidos dela). `pedido_id` e so um vinculo fraco (on delete set null).
--   2. Quem grava o log e o BANCO, nao o navegador:
--        * bipagem com sucesso -> dentro do proprio `pedido_status_id`
--          (uma ida ao banco so: nao pesa na velocidade do operador);
--        * alteracao em massa  -> dentro do `pedido_status_etiquetas`;
--        * bipagens erradas    -> RPC `log_registrar` (uma chamada a mais).
--   3. RETENCAO configuravel pelo administrador na tela de logs:
--      `empresa.log_retencao_dias` (0 = guardar para sempre). A limpeza roda
--      quando a tela de logs e aberta e no botao "Limpar agora" -- assim nao
--      dependemos de pg_cron.
--   4. PERMISSAO: registrar = qualquer usuario logado (o operador bipa);
--      LER / CONFIGURAR / LIMPAR = so ADMIN (via exigir_admin). A tabela em si
--      fica fechada para anon/authenticated: o acesso e so por RPC.
--
-- COMO APLICAR: Supabase Dashboard -> SQL Editor -> colar TODO este arquivo -> Run.
--               (aplique DEPOIS da 20260916000108_importacao_login.sql)
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. RETENCAO NA EMPRESA (dias; 0 = nunca apagar)
-- -----------------------------------------------------------------------------
alter table public.empresa
    add column if not exists log_retencao_dias integer not null default 90;

comment on column public.empresa.log_retencao_dias is
    'Quantos dias de log de conferencia guardar (0 = guardar para sempre). Editado pelo administrador na tela de Logs.';

alter table public.empresa drop constraint if exists ck_empresa_log_retencao;
alter table public.empresa
    add constraint ck_empresa_log_retencao check (log_retencao_dias between 0 and 3650);


-- -----------------------------------------------------------------------------
-- 2. TABELA DE LOG
-- -----------------------------------------------------------------------------
create table if not exists public.log_conferencia (
    id              bigint       not null generated by default as identity,
    empresa_id      bigint       not null references public.empresa (id) on delete cascade,
    layout_controle integer,                          -- fabrica (layout.controle)
    fabrica         varchar(60),                      -- nome da fabrica, copiado
    estagio         integer      not null default 0,  -- 1=CONFERENCIA 2=SAIDA 3=ENTREGA (0 = nao se aplica)
    desfecho        varchar(20)  not null,            -- sucesso | ja_lida | bloqueada | nao_encontrada | massa
    valor_lido      varchar(120),                     -- o que o operador bipou (cru, mesmo quando nao acha nada)
    usuario_id      bigint,                           -- usuario.id
    usuario_login   varchar(50),                      -- usuario.login, copiado
    origem          varchar(20)  not null default 'bipagem',  -- bipagem | massa
    pedido_id       bigint       references public.pedido (id) on delete set null,
    etiqueta        varchar(50),
    ordcompra       varchar(30),
    produto         varchar(70),
    descricao1      varchar(200),
    qtde            numeric(18,3),
    cliente         varchar(70),
    pecliente       varchar(30),
    idbox           integer,
    nmbox           varchar(60),
    status_antes    integer,                          -- PEDIDO.STATUS antes da leitura
    status_novo     integer,                          -- PEDIDO.STATUS depois (null = nao mudou nada)
    mensagem        varchar(200),                     -- texto mostrado ao operador
    criado_em       timestamp    not null default now(),
    constraint pk_log_conferencia primary key (id)
);

comment on table public.log_conferencia is
    'Auditoria da conferencia: uma linha por bipagem (certa ou errada) e por alteracao em massa de status.';
comment on column public.log_conferencia.desfecho is
    'sucesso = avancou de estagio; ja_lida = bipou de novo; bloqueada = fora de ordem; nao_encontrada = codigo inexistente; massa = alteracao pelo menu de contexto.';

/* a tabela nasce com GRANT para anon por causa do "alter default privileges" da
   migracao 00002 -- aqui ela e fechada: o acesso e exclusivamente por RPC. */
alter table public.log_conferencia enable row level security;
revoke all on table public.log_conferencia from anon, authenticated;

create index if not exists ix_log_conferencia_empresa_data on public.log_conferencia (empresa_id, criado_em desc);
create index if not exists ix_log_conferencia_etiqueta     on public.log_conferencia (empresa_id, etiqueta);
create index if not exists ix_log_conferencia_usuario      on public.log_conferencia (empresa_id, usuario_login);
create index if not exists ix_log_conferencia_desfecho     on public.log_conferencia (empresa_id, desfecho);


-- -----------------------------------------------------------------------------
-- 3. GRAVACAO INTERNA (uma linha de log)
-- -----------------------------------------------------------------------------
/**
 * Grava UMA linha de log. De proposito NAO falha quando o pedido nao existe
 * (bipagem de codigo errado): nesse caso fica so o `valor_lido`.
 * Os dados do pedido sao copiados no momento da gravacao.
 */
create or replace function public.log_gravar(
    p_empresa_id   bigint,
    p_usuario_id   bigint,
    p_login        varchar,
    p_controle     integer,
    p_estagio      integer,
    p_desfecho     varchar,
    p_valor_lido   text,
    p_origem       varchar,
    p_pedido_id    bigint,
    p_status_antes integer,
    p_status_novo  integer,
    p_mensagem     varchar
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_id bigint;
begin
    insert into public.log_conferencia (
        empresa_id, layout_controle, fabrica, estagio, desfecho, valor_lido,
        usuario_id, usuario_login, origem, pedido_id, etiqueta, ordcompra, produto,
        descricao1, qtde, cliente, pecliente, idbox, nmbox, status_antes, status_novo, mensagem
    )
    select p_empresa_id,
           p_controle,
           lg.nome,
           coalesce(p_estagio, 0),
           coalesce(nullif(btrim(p_desfecho), ''), 'indefinido'),
           nullif(left(btrim(coalesce(p_valor_lido, '')), 120), ''),
           p_usuario_id,
           p_login,
           coalesce(nullif(btrim(p_origem), ''), 'bipagem'),
           p.id, p.etiqueta, p.ordcompra, p.produto, p.descricao1, p.qtde,
           p.cliente, p.pecliente, p.idbox, bx.nmbox,
           p_status_antes, p_status_novo, left(p_mensagem, 200)
      from (select p_pedido_id as id) v
      left join public.pedido p on p.id = v.id and p.empresa_id = p_empresa_id
      left join public.layout lg on lg.controle = p_controle
      left join public.box    bx on bx.idbox  = p.idbox
    returning log_conferencia.id into v_id;

    return v_id;
end;
$$;

/** Apaga os logs mais antigos que a retencao da empresa. Devolve quantos saiu. */
create or replace function public.logs_limpar_antigos(p_empresa_id bigint, p_dias integer)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_apagados bigint := 0;
begin
    if coalesce(p_dias, 0) <= 0 then
        return 0;   /* 0 = guardar para sempre */
    end if;

    delete from public.log_conferencia l
     where l.empresa_id = p_empresa_id
       and l.criado_em < now() - make_interval(days => p_dias);

    get diagnostics v_apagados = row_count;
    return v_apagados;
end;
$$;

/* a sessao guarda usuario_id, nao o login: helper para nao repetir em cada RPC */
create or replace function public.login_da_sessao(p_sessao public.sessao)
returns varchar
language sql
stable
security definer
set search_path = public, pg_temp
as $$
    select u.login::varchar(50) from public.usuario u where u.id = p_sessao.usuario_id;
$$;


-- -----------------------------------------------------------------------------
-- 4. BIPAGEM ERRADA / REPETIDA -> RPC chamada pelo navegador
-- -----------------------------------------------------------------------------
/**
 * Registra uma leitura que NAO gerou baixa: etiqueta nao encontrada, ja lida ou
 * fora de ordem. Nunca levanta erro por dado faltando -- o log nao pode atrapalhar
 * o operador.
 */
create or replace function public.log_registrar(
    p_token      text,
    p_controle   integer,
    p_estagio    integer,
    p_desfecho   text,
    p_valor_lido text,
    p_pedido_id  bigint default null,
    p_mensagem   text default null
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao    public.sessao := public.sessao_aberta(p_token);
    v_desfecho  varchar(20) := lower(btrim(coalesce(p_desfecho, '')));
    v_controle  integer;
    v_estagio   integer;
    v_antes     integer;
begin
    if v_desfecho not in ('sucesso', 'ja_lida', 'bloqueada', 'nao_encontrada', 'massa') then
        raise exception 'Desfecho de log invalido: %', v_desfecho;
    end if;

    /* a fabrica so entra no log se for desta empresa */
    if exists (select 1 from public.layout l
                where l.controle = p_controle and l.empresa_id = v_sessao.empresa_id) then
        v_controle := p_controle;
    end if;

    /* estagio so aceita 0..3 (fora disso fica 0 = nao se aplica) */
    v_estagio := case when p_estagio between 0 and 3 then p_estagio else 0 end;

    /* status em que a peca estava (mostra "esta etiqueta esta para SAIDA") */
    if p_pedido_id is not null then
        select p.status into v_antes
          from public.pedido p
         where p.id = p_pedido_id and p.empresa_id = v_sessao.empresa_id;
    end if;

    return public.log_gravar(
        v_sessao.empresa_id, v_sessao.usuario_id, public.login_da_sessao(v_sessao),
        v_controle, v_estagio, v_desfecho, p_valor_lido, 'bipagem',
        p_pedido_id, v_antes, null, p_mensagem
    );
end;
$$;


-- -----------------------------------------------------------------------------
-- 5. BIPAGEM COM SUCESSO -> log dentro do proprio pedido_status_id
-- -----------------------------------------------------------------------------
drop function if exists public.pedido_status_id(text, bigint, integer);

create or replace function public.pedido_status_id(
    p_token      text,
    p_id         bigint,
    p_status     integer,
    p_valor_lido text default null,
    p_origem     text default 'bipagem'
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_antes  integer;
    v_layout integer;
    v_etiqueta varchar(50);
    v_linhas integer;
begin
    select p.status, p.idlayout, p.etiqueta
      into v_antes, v_layout, v_etiqueta
      from public.pedido p
     where p.id = p_id
       and p.empresa_id = v_sessao.empresa_id;   /* impede alterar pedido de outra empresa */

    if not found then
        return 0;                                 /* nada a fazer: pedido de outra empresa */
    end if;

    update public.pedido p
       set status = p_status
     where p.id = p_id
       and p.empresa_id = v_sessao.empresa_id;

    get diagnostics v_linhas = row_count;

    /* so registra quando houve mudanca de status de verdade (bipar duas vezes nao e baixa) */
    if v_linhas > 0 and coalesce(v_antes, -1) <> p_status then
        perform public.log_gravar(
            v_sessao.empresa_id, v_sessao.usuario_id, public.login_da_sessao(v_sessao),
            v_layout, p_status, 'sucesso',
            coalesce(nullif(btrim(p_valor_lido), ''), v_etiqueta),
            coalesce(nullif(btrim(p_origem), ''), 'bipagem'),
            p_id, v_antes, p_status, null
        );
    end if;

    return v_linhas;
end;
$$;


-- -----------------------------------------------------------------------------
-- 6. ALTERACAO EM MASSA (menu de contexto) -> log dentro do proprio RPC
-- -----------------------------------------------------------------------------
drop function if exists public.pedido_status_etiquetas(text, text[], integer);

create or replace function public.pedido_status_etiquetas(
    p_token     text,
    p_etiquetas text[],
    p_status    integer,
    p_origem    text default 'massa'
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_login  varchar(50) := public.login_da_sessao(v_sessao);
    v_origem varchar(20) := coalesce(nullif(btrim(p_origem), ''), 'massa');
    v_linhas integer;
    r        record;
begin
    /* 1) registra quem vai mudar (guardando o status de antes) */
    for r in
        select p.id, p.status, p.idlayout, p.etiqueta
          from public.pedido p
         where p.empresa_id = v_sessao.empresa_id
           and p.etiqueta = any (p_etiquetas)
           and p.status <> p_status
    loop
        perform public.log_gravar(
            v_sessao.empresa_id, v_sessao.usuario_id, v_login,
            r.idlayout, p_status, 'massa', r.etiqueta, v_origem,
            r.id, r.status, p_status, 'Alteracao em massa pelo menu de contexto'
        );
    end loop;

    /* 2) altera (legado: UPDATE PEDIDO SET STATUS = x WHERE ETIQUETA IN (...)) */
    update public.pedido p
       set status = p_status
     where p.empresa_id = v_sessao.empresa_id
       and p.etiqueta = any (p_etiquetas);

    get diagnostics v_linhas = row_count;
    return v_linhas;
end;
$$;


-- -----------------------------------------------------------------------------
-- 7. LEITURA DO LOG (somente ADMIN)
-- -----------------------------------------------------------------------------
/**
 * Lista os logs da empresa. Os filtros vazios (null ou '') sao ignorados.
 * De quebra faz a limpeza da retencao -- assim a base se mantem em ordem sem
 * precisar de pg_cron.
 *
 * ATENCAO: o WHERE abaixo e o mesmo do logs_resumo (mantenha os dois juntos).
 */
create or replace function public.logs_listar(
    p_token     text,
    p_de        date    default null,
    p_ate       date    default null,
    p_controle  integer default null,
    p_usuario   text    default null,
    p_desfecho  text    default null,
    p_texto     text    default null,
    p_ordcompra text    default null,
    p_limite    integer default 1000
)
returns table (
    id              bigint,
    criado_em       timestamp,
    fabrica         varchar,
    layout_controle integer,
    estagio         integer,
    desfecho        varchar,
    origem          varchar,
    valor_lido      varchar,
    usuario_login   varchar,
    pedido_id       bigint,
    etiqueta        varchar,
    ordcompra       varchar,
    produto         varchar,
    descricao1      varchar,
    qtde            numeric,
    cliente         varchar,
    pecliente       varchar,
    idbox           integer,
    nmbox           varchar,
    status_antes    integer,
    status_novo     integer,
    mensagem        varchar
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_dias   integer;
begin
    perform public.exigir_admin(v_sessao);

    /* retencao configurada pelo administrador */
    select coalesce(e.log_retencao_dias, 0) into v_dias
      from public.empresa e where e.id = v_sessao.empresa_id;
    perform public.logs_limpar_antigos(v_sessao.empresa_id, v_dias);

    return query
        select l.id, l.criado_em, l.fabrica, l.layout_controle, l.estagio, l.desfecho,
               l.origem, l.valor_lido, l.usuario_login, l.pedido_id, l.etiqueta,
               l.ordcompra, l.produto, l.descricao1, l.qtde, l.cliente, l.pecliente,
               l.idbox, l.nmbox, l.status_antes, l.status_novo, l.mensagem
          from public.log_conferencia l
         where l.empresa_id = v_sessao.empresa_id
           and (p_de        is null or l.criado_em >= p_de::timestamp)
           and (p_ate       is null or l.criado_em <  (p_ate + 1)::timestamp)
           and (p_controle  is null or l.layout_controle = p_controle)
           and (p_usuario   is null or btrim(p_usuario) = ''
                or lower(l.usuario_login) like '%' || lower(btrim(p_usuario)) || '%')
           and (p_desfecho  is null or btrim(p_desfecho) = ''
                or l.desfecho = lower(btrim(p_desfecho)))
           and (p_ordcompra is null or btrim(p_ordcompra) = ''
                or l.ordcompra ilike '%' || btrim(p_ordcompra) || '%')
           and (p_texto     is null or btrim(p_texto) = ''
                or l.etiqueta      ilike '%' || btrim(p_texto) || '%'
                or l.valor_lido    ilike '%' || btrim(p_texto) || '%'
                or l.produto       ilike '%' || btrim(p_texto) || '%'
                or l.descricao1    ilike '%' || btrim(p_texto) || '%'
                or l.ordcompra     ilike '%' || btrim(p_texto) || '%'
                or l.pecliente     ilike '%' || btrim(p_texto) || '%'
                or l.cliente       ilike '%' || btrim(p_texto) || '%'
                or l.usuario_login ilike '%' || btrim(p_texto) || '%')
         order by l.criado_em desc, l.id desc
         limit greatest(coalesce(p_limite, 1000), 1);
end;
$$;

/** Totais do filtro (para a faixa de contadores da tela). Somente ADMIN. */
create or replace function public.logs_resumo(
    p_token     text,
    p_de        date    default null,
    p_ate       date    default null,
    p_controle  integer default null,
    p_usuario   text    default null,
    p_desfecho  text    default null,
    p_texto     text    default null,
    p_ordcompra text    default null
)
returns table (
    total          bigint,
    sucesso        bigint,
    ja_lida        bigint,
    bloqueada      bigint,
    nao_encontrada bigint,
    massa          bigint,
    estagio_1      bigint,
    estagio_2      bigint,
    estagio_3      bigint,
    operadores     bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
begin
    perform public.exigir_admin(v_sessao);

    return query
        select count(*)::bigint,
               count(*) filter (where l.desfecho = 'sucesso')::bigint,
               count(*) filter (where l.desfecho = 'ja_lida')::bigint,
               count(*) filter (where l.desfecho = 'bloqueada')::bigint,
               count(*) filter (where l.desfecho = 'nao_encontrada')::bigint,
               count(*) filter (where l.desfecho = 'massa')::bigint,
               count(*) filter (where l.estagio = 1)::bigint,
               count(*) filter (where l.estagio = 2)::bigint,
               count(*) filter (where l.estagio = 3)::bigint,
               count(distinct l.usuario_login)::bigint
          from public.log_conferencia l
         where l.empresa_id = v_sessao.empresa_id
           and (p_de        is null or l.criado_em >= p_de::timestamp)
           and (p_ate       is null or l.criado_em <  (p_ate + 1)::timestamp)
           and (p_controle  is null or l.layout_controle = p_controle)
           and (p_usuario   is null or btrim(p_usuario) = ''
                or lower(l.usuario_login) like '%' || lower(btrim(p_usuario)) || '%')
           and (p_desfecho  is null or btrim(p_desfecho) = ''
                or l.desfecho = lower(btrim(p_desfecho)))
           and (p_ordcompra is null or btrim(p_ordcompra) = ''
                or l.ordcompra ilike '%' || btrim(p_ordcompra) || '%')
           and (p_texto     is null or btrim(p_texto) = ''
                or l.etiqueta      ilike '%' || btrim(p_texto) || '%'
                or l.valor_lido    ilike '%' || btrim(p_texto) || '%'
                or l.produto       ilike '%' || btrim(p_texto) || '%'
                or l.descricao1    ilike '%' || btrim(p_texto) || '%'
                or l.ordcompra     ilike '%' || btrim(p_texto) || '%'
                or l.pecliente     ilike '%' || btrim(p_texto) || '%'
                or l.cliente       ilike '%' || btrim(p_texto) || '%'
                or l.usuario_login ilike '%' || btrim(p_texto) || '%');
end;
$$;


-- -----------------------------------------------------------------------------
-- 8. RETENCAO: ler / definir / limpar agora (somente ADMIN)
-- -----------------------------------------------------------------------------
/** Dias de retencao configurados (0 = guardar para sempre). */
create or replace function public.logs_retencao(p_token text)
returns integer
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_dias   integer;
begin
    perform public.exigir_admin(v_sessao);

    select coalesce(e.log_retencao_dias, 0) into v_dias
      from public.empresa e where e.id = v_sessao.empresa_id;

    return coalesce(v_dias, 0);
end;
$$;

/** Define os dias de retencao e ja limpa o que passou do prazo novo. */
create or replace function public.logs_retencao_definir(p_token text, p_dias integer)
returns table (dias integer, apagados bigint)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_dias   integer;
    v_apagados bigint;
begin
    perform public.exigir_admin(v_sessao);

    if p_dias is null or p_dias < 0 or p_dias > 3650 then
        raise exception 'Retencao invalida: informe de 0 (nunca apagar) a 3650 dias.';
    end if;

    v_dias := p_dias;

    update public.empresa e
       set log_retencao_dias = v_dias
     where e.id = v_sessao.empresa_id;

    v_apagados := public.logs_limpar_antigos(v_sessao.empresa_id, v_dias);

    return query select v_dias, v_apagados;
end;
$$;

/** Limpa agora usando a retencao configurada (botao "Limpar agora"). */
create or replace function public.logs_limpar(p_token text)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_dias   integer;
begin
    perform public.exigir_admin(v_sessao);

    select coalesce(e.log_retencao_dias, 0) into v_dias
      from public.empresa e where e.id = v_sessao.empresa_id;

    return public.logs_limpar_antigos(v_sessao.empresa_id, v_dias);
end;
$$;


-- -----------------------------------------------------------------------------
-- 9. PERMISSOES
-- -----------------------------------------------------------------------------
/* funcoes internas: ninguem chama pela API */
revoke all on function public.log_gravar(bigint, bigint, varchar, integer, integer, varchar, text, varchar, bigint, integer, integer, varchar) from public;
revoke all on function public.logs_limpar_antigos(bigint, integer) from public;
revoke all on function public.login_da_sessao(public.sessao) from public;

revoke all on function public.log_registrar(text, integer, integer, text, text, bigint, text) from public;
revoke all on function public.logs_listar(text, date, date, integer, text, text, text, text, integer) from public;
revoke all on function public.logs_resumo(text, date, date, integer, text, text, text, text) from public;
revoke all on function public.logs_retencao(text) from public;
revoke all on function public.logs_retencao_definir(text, integer) from public;
revoke all on function public.logs_limpar(text) from public;
revoke all on function public.pedido_status_id(text, bigint, integer, text, text) from public;
revoke all on function public.pedido_status_etiquetas(text, text[], integer, text) from public;

grant execute on function public.log_registrar(text, integer, integer, text, text, bigint, text)          to anon, authenticated;
grant execute on function public.logs_listar(text, date, date, integer, text, text, text, text, integer)  to anon, authenticated;
grant execute on function public.logs_resumo(text, date, date, integer, text, text, text, text)           to anon, authenticated;
grant execute on function public.logs_retencao(text)                                                      to anon, authenticated;
grant execute on function public.logs_retencao_definir(text, integer)                                     to anon, authenticated;
grant execute on function public.logs_limpar(text)                                                        to anon, authenticated;
grant execute on function public.pedido_status_id(text, bigint, integer, text, text)                      to anon, authenticated;
grant execute on function public.pedido_status_etiquetas(text, text[], integer, text)                     to anon, authenticated;

notify pgrst, 'reload schema';


-- -----------------------------------------------------------------------------
-- VERIFICACAO (depois de aplicar)
-- -----------------------------------------------------------------------------
-- -- 1) a tabela e os indices existem:
-- select count(*) as logs from public.log_conferencia;
-- select e.nome, e.log_retencao_dias from public.empresa e order by e.id;
--
-- -- 2) bipagens de hoje, por desfecho:
-- select l.desfecho, count(*), min(l.criado_em) as primeira, max(l.criado_em) as ultima
--   from public.log_conferencia l
--  where l.criado_em >= current_date
--  group by l.desfecho order by 2 desc;
--
-- -- 3) as ultimas 20 leituras com erro (o que o administrador quer caçar):
-- select l.criado_em, l.fabrica, l.estagio, l.desfecho, l.valor_lido,
--        l.etiqueta, l.usuario_login, l.mensagem
--   from public.log_conferencia l
--  where l.desfecho <> 'sucesso'
--  order by l.criado_em desc limit 20;


-- -----------------------------------------------------------------------------
-- ROLLBACK
-- -----------------------------------------------------------------------------
-- drop function if exists public.logs_limpar(text);
-- drop function if exists public.logs_retencao_definir(text, integer);
-- drop function if exists public.logs_retencao(text);
-- drop function if exists public.logs_resumo(text, date, date, integer, text, text, text, text);
-- drop function if exists public.logs_listar(text, date, date, integer, text, text, text, text, integer);
-- drop function if exists public.log_registrar(text, integer, integer, text, text, bigint, text);
-- drop function if exists public.login_da_sessao(public.sessao);
-- drop function if exists public.logs_limpar_antigos(bigint, integer);
-- drop function if exists public.log_gravar(bigint, bigint, varchar, integer, integer, varchar, text, varchar, bigint, integer, integer, varchar);
-- drop table if exists public.log_conferencia;
-- alter table public.empresa drop column if exists log_retencao_dias;
-- (o pedido_status_id / pedido_status_etiquetas antigos voltam rodando a migracao 00101 de novo)
