-- =============================================================================
-- SysConf - Gerenciar arquivos importados (tela "Importacoes")
-- Arquivo : supabase/migrations/20260916000107_importacao_gerenciar.sql
--
-- OBJETIVO (pedido do cliente): uma tela onde ele ve as importacoes feitas,
-- BAIXA o arquivo original, ve informacoes (fabrica, data, quem importou,
-- quantas linhas entraram/foram descartadas) e REMOVE a importacao (apagando
-- os pedidos daquela importacao da base).
--
-- DESENHO:
--   1. `importacao` = cabecalho de cada importacao (um por arquivo importado),
--      com o ARQUIVO ORIGINAL guardado em base64 na propria coluna `conteudo`.
--      Nao usei o Storage do Supabase de proposito: o bucket ficaria acessivel
--      com a chave publica que vai no bundle do site (qualquer um com a chave
--      leria os pedidos dos clientes). Aqui o arquivo fica protegido pela MESMA
--      sessao por token que protege o resto do sistema, e o download passa por
--      RPC. Se um dia o volume crescer muito, migramos para o Storage.
--   2. `pedido.importacao_id` liga cada pedido ao seu cabecalho, com
--      ON DELETE CASCADE: excluir a importacao apaga os pedidos dela.
--   3. BACKFILL: as importacoes antigas (WinForms e a da Romanzza de hoje) viram
--      cabecalhos historicos, com o arquivo sem conteudo (nao temos o original),
--      para a tela ja nascer com o historico visivel.
--
-- PERMISSOES: registrar/listar/baixar = qualquer usuario da empresa (o operador
-- importa). EXCLUIR = so ADMIN (apaga pedidos de verdade).
--
-- COMO APLICAR: Supabase Dashboard -> SQL Editor -> colar TODO este arquivo -> Run.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. CABECALHO DA IMPORTACAO
-- -----------------------------------------------------------------------------
create table if not exists public.importacao (
    id                 bigint    not null generated by default as identity,
    empresa_id         bigint    not null references public.empresa (id) on delete cascade,
    layout_controle    integer   not null references public.layout (controle) on delete cascade,
    nome_arquivo       varchar(255) not null,
    tamanho_bytes      integer   not null default 0,
    codificacao        varchar(20) not null default 'UTF-8',
    linhas_lidas       integer   not null default 0,
    linhas_importadas  integer   not null default 0,
    linhas_descartadas integer   not null default 0,
    usuario_id         bigint,
    usuario_login      varchar(50),
    criado_em          timestamp not null default now(),
    /** Arquivo original em base64 (para o botao "Baixar"). Nulo no historico antigo. */
    conteudo           text,
    constraint pk_importacao primary key (id)
);

comment on table public.importacao is
    'Cabecalho de cada importacao de arquivo: o que foi importado, quando, por quem e o arquivo original.';
comment on column public.importacao.conteudo is
    'Arquivo original em base64 (ate ~4 MB). Nulo quando o arquivo veio do sistema antigo (sem original guardado).';

alter table public.importacao enable row level security;
revoke all on table public.importacao from anon, authenticated;

create index if not exists ix_importacao_empresa_data on public.importacao (empresa_id, criado_em desc);

/* vinculo do pedido com a importacao (excluir a importacao apaga os pedidos) */
alter table public.pedido
    add column if not exists importacao_id bigint references public.importacao (id) on delete cascade;

create index if not exists ix_pedido_importacao on public.pedido (importacao_id);


-- -----------------------------------------------------------------------------
-- 2. BACKFILL: importacoes antigas viram historico
-- -----------------------------------------------------------------------------
insert into public.importacao (
    empresa_id, layout_controle, nome_arquivo, linhas_importadas,
    usuario_login, criado_em, codificacao
)
select p.empresa_id,
       p.idlayout,
       p.arquivo,
       count(*),
       'sistema antigo',
       min(p.datainc),
       'NAO GUARDADO'
from public.pedido p
where p.importacao_id is null
  and p.arquivo is not null
  and btrim(p.arquivo) <> ''
group by p.empresa_id, p.idlayout, p.arquivo;

update public.pedido p
   set importacao_id = i.id
  from public.importacao i
 where p.importacao_id is null
   and i.empresa_id = p.empresa_id
   and i.layout_controle = p.idlayout
   and i.nome_arquivo = p.arquivo;


-- -----------------------------------------------------------------------------
-- 3. RPCs
-- -----------------------------------------------------------------------------

/** Registra a importacao e devolve o id (chamada antes de inserir os pedidos). */
create or replace function public.importacao_registrar(
    p_token              text,
    p_controle           integer,
    p_nome_arquivo       text,
    p_tamanho_bytes      integer,
    p_codificacao        text,
    p_linhas_lidas       integer,
    p_linhas_importadas  integer,
    p_linhas_descartadas integer,
    p_conteudo_base64    text
)
returns bigint
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_nome   text := btrim(coalesce(p_nome_arquivo, ''));
    v_arquivo text := nullif(p_conteudo_base64, '');
    v_id     bigint;
begin
    if v_nome = '' or length(v_nome) > 255 then
        raise exception 'Nome de arquivo invalido.';
    end if;
    if not exists (
        select 1 from public.layout l
        where l.controle = p_controle and l.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Fabrica invalida para esta empresa.' using errcode = 'P0002';
    end if;

    /* guarda o arquivo, mas nao aceita arquivo gigante no banco */
    if v_arquivo is not null and length(v_arquivo) > 5500000 then
        v_arquivo := null;
    end if;

    insert into public.importacao (
        empresa_id, layout_controle, nome_arquivo, tamanho_bytes, codificacao,
        linhas_lidas, linhas_importadas, linhas_descartadas,
        usuario_id, usuario_login, conteudo
    )
    values (
        v_sessao.empresa_id, p_controle, v_nome, greatest(coalesce(p_tamanho_bytes, 0), 0),
        coalesce(nullif(btrim(p_codificacao), ''), 'UTF-8'),
        greatest(coalesce(p_linhas_lidas, 0), 0),
        greatest(coalesce(p_linhas_importadas, 0), 0),
        greatest(coalesce(p_linhas_descartadas, 0), 0),
        v_sessao.usuario_id, v_sessao.login, v_arquivo
    )
    returning importacao.id into v_id;

    return v_id;
end;
$$;

/** Lista as importacoes da empresa (mais recentes primeiro). */
create or replace function public.importacoes_listar(p_token text)
returns table (
    id                 bigint,
    criado_em          timestamp,
    fabrica            varchar,
    layout_controle    integer,
    nome_arquivo       varchar,
    tamanho_bytes      integer,
    codificacao        varchar,
    linhas_lidas       integer,
    linhas_importadas  integer,
    linhas_descartadas integer,
    usuario_login      varchar,
    pedidos            bigint,
    tem_arquivo        boolean
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
begin
    return query
        select i.id,
               i.criado_em,
               l.nome::varchar,
               i.layout_controle,
               i.nome_arquivo,
               i.tamanho_bytes,
               i.codificacao,
               i.linhas_lidas,
               i.linhas_importadas,
               i.linhas_descartadas,
               i.usuario_login,
               (select count(*) from public.pedido p where p.importacao_id = i.id) as pedidos,
               (i.conteudo is not null) as tem_arquivo
        from public.importacao i
        join public.layout l on l.controle = i.layout_controle
        where i.empresa_id = v_sessao.empresa_id
        order by i.criado_em desc
        limit 300;
end;
$$;

/** Devolve o arquivo original para o download. */
create or replace function public.importacao_arquivo(p_token text, p_id bigint)
returns table (
    nome_arquivo varchar,
    conteudo     text
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
begin
    return query
        select i.nome_arquivo, i.conteudo
        from public.importacao i
        where i.id = p_id and i.empresa_id = v_sessao.empresa_id;
end;
$$;

/** Exclui a importacao e, em cascata, os pedidos que vieram dela. */
create or replace function public.importacao_excluir(p_token text, p_id bigint)
returns table (
    pedidos_apagados bigint
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao  public.sessao := public.sessao_aberta(p_token);
    v_pedidos bigint;
begin
    perform public.exigir_admin(v_sessao);

    if not exists (
        select 1 from public.importacao i
        where i.id = p_id and i.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Importacao nao encontrada nesta empresa.' using errcode = 'P0002';
    end if;

    select count(*) into v_pedidos from public.pedido p where p.importacao_id = p_id;

    delete from public.importacao i where i.id = p_id;

    return query select v_pedidos;
end;
$$;


-- -----------------------------------------------------------------------------
-- 4. pedidos_inserir passa a gravar de qual importacao veio cada pedido
-- -----------------------------------------------------------------------------
drop function if exists public.pedidos_inserir(text, integer, jsonb);

create or replace function public.pedidos_inserir(
    p_token         text,
    p_idlayout      integer,
    p_pedidos       jsonb,
    p_importacao_id bigint default null
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao    public.sessao := public.sessao_aberta(p_token);
    v_inseridos integer;
begin
    if p_pedidos is null or jsonb_typeof(p_pedidos) <> 'array' then
        raise exception 'Nenhuma linha para importar.';
    end if;

    if not exists (
        select 1 from public.layout l
        where l.controle = p_idlayout and l.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Fabrica invalida para esta empresa.' using errcode = 'P0002';
    end if;

    if p_importacao_id is not null and not exists (
        select 1 from public.importacao i
        where i.id = p_importacao_id and i.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Importacao invalida para esta empresa.' using errcode = 'P0002';
    end if;

    insert into public.pedido (
        arquivo, ordcompra, cliente, pecliente, produto, descricao1, qtde, etiqueta,
        volume, sequencia, status, datainc, idlayout, idbox, flbloqueio, pecomputador,
        pecoletor, codcliente, volume2, idgrupo, empresa_id, importacao_id
    )
    select x.arquivo, x.ordcompra, x.cliente, x.pecliente, x.produto, x.descricao1,
           coalesce(x.qtde, 0), x.etiqueta, coalesce(x.volume, 0), coalesce(x.sequencia, 0),
           coalesce(x.status, 0), coalesce(x.datainc, now()::timestamp), p_idlayout,
           coalesce(x.idbox, 1), coalesce(x.flbloqueio, false), x.pecomputador,
           x.pecoletor, x.codcliente, x.volume2, x.idgrupo, v_sessao.empresa_id,
           p_importacao_id
    from jsonb_to_recordset(p_pedidos) as x(
        arquivo      varchar,
        ordcompra    varchar,
        cliente      varchar,
        pecliente    varchar,
        produto      varchar,
        descricao1   varchar,
        qtde         numeric,
        etiqueta     varchar,
        volume       numeric,
        sequencia    numeric,
        status       integer,
        datainc      timestamp,
        idbox        integer,
        flbloqueio   boolean,
        pecomputador varchar,
        pecoletor    varchar,
        codcliente   varchar,
        volume2      numeric,
        idgrupo      integer
    );

    /* registra quantos pedidos entraram nesta importacao */
    if p_importacao_id is not null then
        update public.importacao i
           set linhas_importadas = (select count(*) from public.pedido p where p.importacao_id = p_importacao_id)
         where i.id = p_importacao_id;
    end if;

    get diagnostics v_inseridos = row_count;
    return v_inseridos;
end;
$$;


-- -----------------------------------------------------------------------------
-- 5. PERMISSOES
-- -----------------------------------------------------------------------------
revoke all on function public.importacao_registrar(text, integer, text, integer, text, integer, integer, integer, text) from public;
revoke all on function public.importacoes_listar(text) from public;
revoke all on function public.importacao_arquivo(text, bigint) from public;
revoke all on function public.importacao_excluir(text, bigint) from public;
revoke all on function public.pedidos_inserir(text, integer, jsonb, bigint) from public;

grant execute on function public.importacao_registrar(text, integer, text, integer, text, integer, integer, integer, text) to anon, authenticated;
grant execute on function public.importacoes_listar(text)                          to anon, authenticated;
grant execute on function public.importacao_arquivo(text, bigint)                  to anon, authenticated;
grant execute on function public.importacao_excluir(text, bigint)                  to anon, authenticated;
grant execute on function public.pedidos_inserir(text, integer, jsonb, bigint)     to anon, authenticated;

notify pgrst, 'reload schema';


-- -----------------------------------------------------------------------------
-- VERIFICACAO (depois de aplicar)
-- -----------------------------------------------------------------------------
-- select count(*) as importacoes from public.importacao;                     -- historico do backfill
-- select count(*) as pedidos_sem_importacao from public.pedido where importacao_id is null;
-- select i.id, l.nome, i.nome_arquivo, i.linhas_importadas, i.usuario_login, i.criado_em
--   from public.importacao i join public.layout l on l.controle = i.layout_controle
--  order by i.criado_em desc limit 5;


-- -----------------------------------------------------------------------------
-- ROLLBACK
-- -----------------------------------------------------------------------------
-- alter table public.pedido drop column if exists importacao_id;
-- drop function if exists public.importacao_excluir(text, bigint);
-- drop function if exists public.importacao_arquivo(text, bigint);
-- drop function if exists public.importacoes_listar(text);
-- drop function if exists public.importacao_registrar(text, integer, text, integer, text, integer, integer, integer, text);
-- drop table if exists public.importacao;
-- (o pedidos_inserir antigo volta rodando a migracao 00101 de novo)
