-- =============================================================================
-- SysConf - Multi-empresa (tenant) no schema legado
-- Arquivo : supabase/migrations/20260914000006_empresa_multitenant.sql
--
-- Contexto: o sistema passa a ser usado por mais de uma empresa e a empresa é
-- identificada pela URL (/sysconf/<slug>/login). O cadastro de empresa é feito
-- SOMENTE pelo banco; usuários e perfis são geridos pela própria empresa logada.
-- O app WinForms será desativado — a aplicação de referência é o web (web/).
--
-- Decisões aplicadas:
--   * `usuario.perfil` novo (ADMIN | OPERADOR); a coluna legada `nivel` fica intacta.
--   * senha permanece em texto plano (o login legado compara direto) — ver AVISO.
--   * login do usuário passa a ser único POR EMPRESA.
--   * `layout.controle` continua sendo a chave global (é a FK de pedido.idlayout),
--     apenas ganhou empresa_id.
--
-- AVISO DE SEGURANÇA: com RLS desabilitado e a chave publishable no navegador,
-- qualquer cliente pode ler/gravar estas tabelas diretamente (inclusive criar um
-- ADMIN). A correção definitiva é Supabase Auth (JWT) + RLS por empresa — fase 2.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. TABELA DE EMPRESAS (cadastro via banco)
-- -----------------------------------------------------------------------------
create table if not exists public.empresa (
    id        bigint      not null generated by default as identity,
    slug      varchar(40) not null,                -- o que vai na URL: /sysconf/<slug>/login
    nome      varchar(120) not null,
    ativo     integer     not null default 1,
    criado_em timestamp   not null default now(),
    constraint pk_empresa primary key (id)
);

create unique index if not exists ux_empresa_slug on public.empresa (lower(slug));

comment on table public.empresa is
    'Empresas atendidas pelo SysConf. Cadastro feito diretamente no banco (não há tela).';


-- -----------------------------------------------------------------------------
-- 2. EMPRESAS INICIAIS
--    novomundo  -> dados reais (importação da Criare)
--    homologacao -> layout "CSV Padrão" + as linhas de teste do arquivo pedidos-teste.csv
-- Para incluir outra empresa:
--   insert into public.empresa (slug, nome) values ('<slug>', '<Nome>');
-- -----------------------------------------------------------------------------
insert into public.empresa (slug, nome, ativo) values
    ('novomundo',   'Novo Mundo', 1),
    ('homologacao', 'Homologação', 1)
on conflict (lower(slug)) do nothing;


-- -----------------------------------------------------------------------------
-- 3. VÍNCULO COM A EMPRESA
-- -----------------------------------------------------------------------------
alter table public.usuario add column if not exists empresa_id bigint references public.empresa (id);
alter table public.usuario add column if not exists perfil     varchar(20) not null default 'OPERADOR';
alter table public.pedido  add column if not exists empresa_id bigint references public.empresa (id);
alter table public.layout  add column if not exists empresa_id bigint references public.empresa (id);
alter table public.box     add column if not exists empresa_id bigint references public.empresa (id);


-- -----------------------------------------------------------------------------
-- 4. ATRIBUIÇÃO DOS DADOS EXISTENTES
-- -----------------------------------------------------------------------------
update public.layout  set empresa_id = (select id from public.empresa where slug = 'homologacao')
    where empresa_id is null and controle = 3;                       -- CSV Padrão
update public.layout  set empresa_id = (select id from public.empresa where slug = 'novomundo')
    where empresa_id is null;
update public.pedido  set empresa_id = (select id from public.empresa where slug = 'homologacao')
    where empresa_id is null and idlayout = 3;                        -- linhas de teste
update public.pedido  set empresa_id = (select id from public.empresa where slug = 'novomundo')
    where empresa_id is null;
update public.box     set empresa_id = (select id from public.empresa where slug = 'novomundo') where empresa_id is null;
update public.usuario set empresa_id = (select id from public.empresa where slug = 'novomundo') where empresa_id is null;

update public.usuario set perfil = 'ADMIN' where lower(login) = 'admin';


-- -----------------------------------------------------------------------------
-- 5. LOGIN ÚNICO POR EMPRESA + USUÁRIOS DE TESTE
-- -----------------------------------------------------------------------------
drop index if exists public.ux_usuario_login;

create unique index if not exists ux_usuario_empresa_login
    on public.usuario (empresa_id, lower(login));

insert into public.usuario (empresa_id, login, senha, nivel, nome, perfil)
select e.id, v.login, v.senha, v.nivel, v.nome, v.perfil
from (values
        ('novomundo',   'OPERADOR', 'trocar@123', 'OPERADOR', 'Operador Novo Mundo',        'OPERADOR'),
        ('homologacao', 'ADMIN',    'trocar@123', 'ADMIN',    'Administrador Homologação',  'ADMIN'),
        ('homologacao', 'OPERADOR', 'trocar@123', 'OPERADOR', 'Operador Homologação',       'OPERADOR')
     ) as v(slug, login, senha, nivel, nome, perfil)
join public.empresa e on lower(e.slug) = v.slug
on conflict (empresa_id, lower(login)) do nothing;

-- garante que os perfis fiquem coerentes com o login
update public.usuario set perfil = 'ADMIN'    where lower(login) = 'admin';
update public.usuario set perfil = 'OPERADOR' where lower(login) = 'operador' and perfil is distinct from 'OPERADOR';


-- -----------------------------------------------------------------------------
-- 6. ÍNDICES POR EMPRESA
-- -----------------------------------------------------------------------------
create index if not exists ix_pedido_empresa  on public.pedido  (empresa_id);
create index if not exists ix_layout_empresa  on public.layout  (empresa_id);
create index if not exists ix_box_empresa     on public.box     (empresa_id);
create index if not exists ix_usuario_empresa on public.usuario (empresa_id);


-- -----------------------------------------------------------------------------
-- 7. PERMISSÕES
-- -----------------------------------------------------------------------------
grant select, insert, update, delete on public.empresa to anon, authenticated, service_role;
alter table public.empresa disable row level security;


-- -----------------------------------------------------------------------------
-- 8. VERIFICAÇÃO
-- -----------------------------------------------------------------------------
-- select slug, nome, ativo from public.empresa order by slug;
-- select e.slug, u.login, u.perfil from public.usuario u join public.empresa e on e.id = u.empresa_id order by e.slug, u.login;
-- select e.slug, count(p.id) from public.empresa e left join public.pedido p on p.empresa_id = e.id group by e.slug;
-- select e.slug, count(l.controle) from public.empresa e left join public.layout l on l.empresa_id = e.id group by e.slug;


-- -----------------------------------------------------------------------------
-- 9. ROLLBACK (parcial — não remove dados já gravados com empresa_id)
-- -----------------------------------------------------------------------------
-- drop index if exists public.ix_pedido_empresa;
-- drop index if exists public.ix_layout_empresa;
-- drop index if exists public.ix_box_empresa;
-- drop index if exists public.ix_usuario_empresa;
-- drop index if exists public.ux_usuario_empresa_login;
-- create unique index if not exists ux_usuario_login on public.usuario (lower(login));
-- alter table public.usuario drop column if exists perfil;
-- alter table public.usuario drop column if exists empresa_id;
-- alter table public.pedido  drop column if exists empresa_id;
-- alter table public.layout  drop column if exists empresa_id;
-- alter table public.box     drop column if exists empresa_id;
-- drop table if exists public.empresa;
