-- =============================================================================
-- SysConf - Cadastro de fabrica e layout do arquivo (mapa de colunas)
-- Arquivo : supabase/migrations/20260916000104_fabricas_e_layout_mapa.sql
--
-- PROBLEMA: `layout` (fabrica) nascia apenas por SQL ou pelo catalogo do
-- autocadastro, e o mapa de colunas do arquivo de cada fabrica estava no CODIGO
-- do site (web/src/lib/parsers.ts -> PARSERS). Cada fabrica nova exigia deploy.
--
-- SOLUCAO: a empresa (administrador) cadastra a fabrica e define o layout
-- importando um arquivo real, com deteccao automatica de delimitador e ajuste
-- manual (mesma ideia do "Importar dados TXT" do Excel). O mapa fica no banco,
-- em `layout_mapa`, e a importacao passa a usar o layout salvo.
--
-- Decisoes do cliente (16/09/2026):
--   1. uma fabrica = UM layout (variacoes entram como fabricas separadas,
--      igual ao legado: "Italinea" e "Italinea Loja")  -> unique em layout_controle
--   2. arquivo posicional (largura fixa) fica para a fase 2
--   3. so o ADMINISTRADOR cria fabrica e define layout (o operador so importa)
--   4. codificacao: UTF-8 (se o arquivo vier em ANSI, a tela avisa)
--
-- O navegador continua SEM acesso direto as tabelas: escrita e leitura passam
-- por estes RPCs (o GRANT de `layout` para anon/authenticated segue revogado).
--
-- COMO APLICAR: Supabase Dashboard -> SQL Editor -> colar TODO este arquivo -> Run.
-- =============================================================================


-- -----------------------------------------------------------------------------
-- 1. MAPA DO LAYOUT (uma linha por fabrica)
-- -----------------------------------------------------------------------------
create table if not exists public.layout_mapa (
    id              bigint    not null generated by default as identity,
    empresa_id      bigint    not null references public.empresa (id) on delete cascade,
    layout_controle integer   not null references public.layout (controle) on delete cascade,
    delimitador     varchar(4)  not null default ';',
    linha_inicial   integer     not null default 1,        -- 1 = primeira linha do arquivo
    tem_cabecalho   boolean     not null default false,
    codificacao     varchar(20) not null default 'UTF-8',
    campos          jsonb       not null default '{}'::jsonb,  -- {"etiqueta":6,"produto":3,...}
    criado_em       timestamp   not null default now(),
    atualizado_em   timestamp   not null default now(),
    constraint pk_layout_mapa primary key (id),
    constraint ux_layout_mapa_fabrica unique (layout_controle)  -- decisao 1
);

comment on table public.layout_mapa is
    'Como ler o arquivo de cada fabrica: delimitador, primeira linha util, cabecalho e o mapa campo -> coluna.';
comment on column public.layout_mapa.campos is
    'Indice (0-based) da coluna do arquivo para cada campo: etiqueta, produto, descricao1, qtde, volume, sequencia, pecliente, ordcompra, cliente.';

alter table public.layout_mapa enable row level security;
revoke all on table public.layout_mapa from anon, authenticated;


-- -----------------------------------------------------------------------------
-- 2. HELPERS
-- -----------------------------------------------------------------------------
/** Valida e normaliza o mapa de campos recebido do navegador. */
create or replace function public.layout_campos_validar(p_campos jsonb)
returns jsonb
language plpgsql
immutable
as $$
declare
    v_permitidos text[] := array['ordcompra','cliente','pecliente','produto','descricao1','qtde','etiqueta','volume','sequencia'];
    v_chave text;
    v_valor jsonb;
    v_saida jsonb := '{}'::jsonb;
    v_indice integer;
begin
    if p_campos is null or jsonb_typeof(p_campos) <> 'object' then
        raise exception 'Mapa de colunas invalido.';
    end if;

    for v_chave, v_valor in select * from jsonb_each(p_campos) loop
        if not (v_chave = any (v_permitidos)) then
            raise exception 'Campo desconhecido no layout: %', v_chave;
        end if;
        if v_valor is null or v_valor = 'null'::jsonb then
            continue;
        end if;
        begin
            v_indice := (v_valor #>> '{}')::integer;
        exception when others then
            raise exception 'Coluna invalida para o campo %: %', v_chave, v_valor #>> '{}';
        end;
        if v_indice < 0 or v_indice > 500 then
            raise exception 'Coluna fora do intervalo para o campo %: %', v_chave, v_indice;
        end if;
        v_saida := v_saida || jsonb_build_object(v_chave, v_indice);
    end loop;

    /* a etiqueta e a chave da conferencia: sem ela o layout nao serve */
    if not (v_saida ? 'etiqueta') then
        raise exception 'Escolha qual coluna do arquivo tem a ETIQUETA (codigo de barras).';
    end if;

    return v_saida;
end;
$$;

revoke all on function public.layout_campos_validar(jsonb) from public;


-- -----------------------------------------------------------------------------
-- 3. RPCs DE FABRICA (escrita somente ADMIN)
-- -----------------------------------------------------------------------------
/** Lista completa para a tela de fabricas: situacao, pedidos e se tem layout. */
create or replace function public.fabricas_admin(p_token text)
returns table (
    controle       integer,
    nome           varchar,
    ativo          integer,
    pedidos        bigint,
    tem_layout     boolean,
    layout_campos  jsonb,
    layout_delim   varchar
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
begin
    perform public.exigir_admin(v_sessao);

    return query
        select l.controle,
               l.nome,
               l.flativo,
               (select count(*) from public.pedido p where p.idlayout = l.controle) as pedidos,
               (m.id is not null) as tem_layout,
               m.campos,
               m.delimitador
        from public.layout l
        left join public.layout_mapa m on m.layout_controle = l.controle
        where l.empresa_id = v_sessao.empresa_id
        order by l.nome;
end;
$$;

/** Cria a fabrica para a empresa da sessao e devolve o `controle` gerado. */
create or replace function public.fabrica_criar(p_token text, p_nome text)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_nome   text := btrim(coalesce(p_nome, ''));
    v_base   integer;
    v_novo   integer;
begin
    perform public.exigir_admin(v_sessao);

    if length(v_nome) < 2 or length(v_nome) > 60 then
        raise exception 'O nome da fabrica deve ter de 2 a 60 caracteres.';
    end if;
    if exists (
        select 1 from public.layout l
        where l.empresa_id = v_sessao.empresa_id and lower(l.nome) = lower(v_nome)
    ) then
        raise exception 'Ja existe uma fabrica chamada "%" nesta empresa.', v_nome;
    end if;

    /* `controle` e PK GLOBAL: serializa o calculo (dois cadastros simultaneos) */
    perform pg_advisory_xact_lock(hashtext('sysconf.layout.controle'));
    select coalesce(max(l.controle), 0) + 1 into v_novo from public.layout l;

    insert into public.layout (controle, nome, flativo, empresa_id)
    values (v_novo, v_nome, 1, v_sessao.empresa_id);

    return v_novo;
end;
$$;

/** Renomeia e/ou ativa-desativa a fabrica. */
create or replace function public.fabrica_atualizar(
    p_token    text,
    p_controle integer,
    p_nome     text,
    p_ativo    integer
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_nome   text := btrim(coalesce(p_nome, ''));
    v_linhas integer;
begin
    perform public.exigir_admin(v_sessao);

    if not exists (
        select 1 from public.layout l
        where l.controle = p_controle and l.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Fabrica nao encontrada nesta empresa.' using errcode = 'P0002';
    end if;

    if length(v_nome) < 2 or length(v_nome) > 60 then
        raise exception 'O nome da fabrica deve ter de 2 a 60 caracteres.';
    end if;
    if exists (
        select 1 from public.layout l
        where l.empresa_id = v_sessao.empresa_id
          and lower(l.nome) = lower(v_nome)
          and l.controle <> p_controle
    ) then
        raise exception 'Ja existe uma fabrica chamada "%" nesta empresa.', v_nome;
    end if;
    if coalesce(p_ativo, 1) not in (0, 1) then
        raise exception 'Situacao invalida.';
    end if;

    update public.layout l
       set nome = v_nome, flativo = coalesce(p_ativo, l.flativo)
     where l.controle = p_controle;

    get diagnostics v_linhas = row_count;
    return v_linhas;
end;
$$;

/** Exclui a fabrica - somente se ela nao tiver nenhum pedido importado. */
create or replace function public.fabrica_excluir(p_token text, p_controle integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_pedidos bigint;
    v_linhas  integer;
begin
    perform public.exigir_admin(v_sessao);

    if not exists (
        select 1 from public.layout l
        where l.controle = p_controle and l.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Fabrica nao encontrada nesta empresa.' using errcode = 'P0002';
    end if;

    select count(*) into v_pedidos from public.pedido p where p.idlayout = p_controle;
    if v_pedidos > 0 then
        raise exception 'Esta fabrica tem % pedido(s) importado(s). Desative em vez de excluir.', v_pedidos;
    end if;

    delete from public.layout l where l.controle = p_controle;
    get diagnostics v_linhas = row_count;
    return v_linhas;
end;
$$;


-- -----------------------------------------------------------------------------
-- 4. RPCs DO LAYOUT (ler: qualquer usuario da empresa · gravar: ADMIN)
-- -----------------------------------------------------------------------------
/** Leitura usada pela importacao (operador tambem precisa). */
create or replace function public.layout_da_fabrica(p_token text, p_controle integer)
returns table (
    delimitador   varchar,
    linha_inicial integer,
    tem_cabecalho boolean,
    campos        jsonb
)
language plpgsql
stable
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
begin
    return query
        select m.delimitador, m.linha_inicial, m.tem_cabecalho, m.campos
        from public.layout_mapa m
        join public.layout l on l.controle = m.layout_controle
        where m.layout_controle = p_controle
          and l.empresa_id = v_sessao.empresa_id;
end;
$$;

/** Grava (ou substitui) o layout da fabrica. */
create or replace function public.layout_salvar(
    p_token         text,
    p_controle      integer,
    p_delimitador   text,
    p_linha_inicial integer,
    p_tem_cabecalho boolean,
    p_campos        jsonb
)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_delim  text := case p_delimitador
                        when '\t' then E'\t'
                        when 'tab' then E'\t'
                        else coalesce(nullif(btrim(p_delimitador), ''), ';')
                     end;
    v_linha  integer := coalesce(p_linha_inicial, 1);
    v_campos jsonb   := public.layout_campos_validar(p_campos);
    v_id     bigint;
begin
    perform public.exigir_admin(v_sessao);

    if not exists (
        select 1 from public.layout l
        where l.controle = p_controle and l.empresa_id = v_sessao.empresa_id
    ) then
        raise exception 'Fabrica nao encontrada nesta empresa.' using errcode = 'P0002';
    end if;

    if v_delim not in (';', ',', '|', E'\t') then
        raise exception 'Delimitador invalido. Use ponto e virgula, virgula, barra vertical ou TAB.';
    end if;
    if v_linha < 1 or v_linha > 100 then
        raise exception 'A linha inicial deve ficar entre 1 e 100.';
    end if;

    insert into public.layout_mapa (empresa_id, layout_controle, delimitador, linha_inicial, tem_cabecalho, codificacao, campos)
    values (v_sessao.empresa_id, p_controle, v_delim, v_linha, coalesce(p_tem_cabecalho, false), 'UTF-8', v_campos)
    on conflict (layout_controle) do update
        set delimitador   = excluded.delimitador,
            linha_inicial = excluded.linha_inicial,
            tem_cabecalho = excluded.tem_cabecalho,
            codificacao   = excluded.codificacao,
            campos        = excluded.campos,
            atualizado_em = now()
    returning layout_mapa.id into v_id;

    return v_id;
end;
$$;

/** Remove o layout (a fabrica volta a ser lida pelo modo generico). */
create or replace function public.layout_excluir(p_token text, p_controle integer)
returns integer
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
    v_sessao public.sessao := public.sessao_aberta(p_token);
    v_linhas integer;
begin
    perform public.exigir_admin(v_sessao);

    delete from public.layout_mapa m
     where m.layout_controle = p_controle
       and m.empresa_id = v_sessao.empresa_id;

    get diagnostics v_linhas = row_count;
    return v_linhas;
end;
$$;


-- -----------------------------------------------------------------------------
-- 5. PERMISSOES
-- -----------------------------------------------------------------------------
revoke all on function public.fabricas_admin(text) from public;
revoke all on function public.fabrica_criar(text, text) from public;
revoke all on function public.fabrica_atualizar(text, integer, text, integer) from public;
revoke all on function public.fabrica_excluir(text, integer) from public;
revoke all on function public.layout_da_fabrica(text, integer) from public;
revoke all on function public.layout_salvar(text, integer, text, integer, boolean, jsonb) from public;
revoke all on function public.layout_excluir(text, integer) from public;

grant execute on function public.fabricas_admin(text)                                        to anon, authenticated;
grant execute on function public.fabrica_criar(text, text)                                   to anon, authenticated;
grant execute on function public.fabrica_atualizar(text, integer, text, integer)             to anon, authenticated;
grant execute on function public.fabrica_excluir(text, integer)                              to anon, authenticated;
grant execute on function public.layout_da_fabrica(text, integer)                            to anon, authenticated;
grant execute on function public.layout_salvar(text, integer, text, integer, boolean, jsonb) to anon, authenticated;
grant execute on function public.layout_excluir(text, integer)                               to anon, authenticated;

notify pgrst, 'reload schema';


-- -----------------------------------------------------------------------------
-- VERIFICACAO (depois de aplicar)
-- -----------------------------------------------------------------------------
-- select * from public.layout_mapa;                       -- deve estar vazia
-- select public.fabrica_criar('<token>', 'Fabrica Teste');
-- select public.layout_salvar('<token>', <controle>, ';', 1, false, '{"etiqueta":6,"produto":3,"qtde":5}');
-- select * from public.layout_da_fabrica('<token>', <controle>);
-- limpeza: select public.fabrica_excluir('<token>', <controle>);
-- erro esperado: layout_salvar sem etiqueta -> 'Escolha qual coluna do arquivo tem a ETIQUETA'


-- -----------------------------------------------------------------------------
-- ROLLBACK
-- -----------------------------------------------------------------------------
-- drop function if exists public.layout_excluir(text, integer);
-- drop function if exists public.layout_salvar(text, integer, text, integer, boolean, jsonb);
-- drop function if exists public.layout_da_fabrica(text, integer);
-- drop function if exists public.fabrica_excluir(text, integer);
-- drop function if exists public.fabrica_atualizar(text, integer, text, integer);
-- drop function if exists public.fabrica_criar(text, text);
-- drop function if exists public.fabricas_admin(text);
-- drop function if exists public.layout_campos_validar(jsonb);
-- drop table if exists public.layout_mapa;
